/* V9 CALENDAR 10.12 FAST - performance layer over 10.11 */
(function(){'use strict';
const MAX=5040,norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim(),pad=n=>String(n).padStart(2,'0'),dk=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,from=k=>{const[y,m,d]=String(k).split('-').map(Number);return new Date(y,m-1,d,12)},add=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x},pk=(a,b)=>[String(a),String(b)].sort().join('|');
function slot(t){if(!t)return'';const c=norm(t.home_court||''),d=String(dayIndex(t.home_match_day)),tm=String(normalizeTime(t.home_match_time)||'');return c&&d!=='undefined'&&tm?`${c}|${d}|${tm}`:''}
function fac(t,v){if(t?.facility_id)return`id:${t.facility_id}`;const a=[t?.club_address,t?.club_city].map(norm).filter(Boolean).join('|');return a?`addr:${a}`:`court:${norm(v||t?.home_court||t?.id||'')}`}
const dur=t=>Number(t?.match_slot_minutes||document.getElementById('defaultSlotMinutes')?.value||120);
function overlap(a,b){const x=+new Date(a.scheduled_at),y=+new Date(b.scheduled_at);return x<y+(b._duration_minutes||120)*60000&&y<x+(a._duration_minutes||120)*60000}
const same=(a,b)=>pk(a?.home_team_id,a?.away_team_id)===pk(b?.home_team_id,b?.away_team_id);
function conflict(a,b){if(!a||!b||same(a,b)||!overlap(a,b))return false;if(a._shared_home_slot_key&&a._shared_home_slot_key===b._shared_home_slot_key)return true;return!!a._facility_key&&a._facility_key===b._facility_key}
function blackout(f,code){const date=dk(new Date(f.scheduled_at));return(blackouts||[]).some(b=>String(b.blackout_date||'').slice(0,10)===date&&(String(b.competition_code||'ALL').toUpperCase()==='ALL'||String(b.competition_code||'').toUpperCase()===String(code).toUpperCase()))}
function occ(anchor,t){const di=dayIndex(t.home_match_day),tm=normalizeTime(t.home_match_time);if(di===undefined||!tm||!String(t.home_court||'').trim())throw Error(`Completa giorno, ora e campo di casa per ${t.name}.`);const d=new Date(anchor);let g=0;while(d.getDay()!==di&&g++<7)d.setDate(d.getDate()+1);const date=dk(d),scheduled_at=localDateTimeToISO(date,tm),local=localPartsFromISO(scheduled_at);return{scheduled_at,local}}
function mk(g,r,h,a,anchor,code){const o=occ(anchor,h),f={competition_code:code,phase:'Girone',group_id:g.id,round_number:r,home_team_id:h.id,away_team_id:a.id,scheduled_at:o.scheduled_at,venue:h.home_court,_home_name:h.name,_away_name:a.name,_configured_day:h.home_match_day,_configured_time:normalizeTime(h.home_match_time),_local_date:o.local.date,_local_time:o.local.time,_local_weekday:o.local.weekday,_round_anchor:dk(anchor),_facility_key:fac(h,h.home_court),_shared_home_slot_key:slot(h),_duration_minutes:dur(h)};if(typeof assertHomeRule==='function')assertHomeRule(f);return f}
function ext(code){return(allFixtures||[]).filter(x=>String(x.competition_code)!==String(code)).map(x=>{const h=teams.find(t=>String(t.id)===String(x.home_team_id)),a=teams.find(t=>String(t.id)===String(x.away_team_id));if(!h||!x.scheduled_at)return null;return{...x,_home_name:h.name,_away_name:a?.name||x.away_placeholder||'Ospite',_facility_key:fac(h,x.venue||h.home_court),_shared_home_slot_key:slot(h),_duration_minutes:dur(h)}}).filter(Boolean)}
function clean(rows,other){for(let i=0;i<rows.length;i++){for(let j=i+1;j<rows.length;j++)if(conflict(rows[i],rows[j]))return false;for(const e of other||[])if(conflict(rows[i],e))return false}return true}
function rr(list){const a=[...list];if(a.length%2)a.push({__bye:true,id:'BYE'});const out=[];for(let r=0;r<a.length-1;r++){const p=[];for(let i=0;i<a.length/2;i++){const x=a[i],y=a[a.length-1-i];if(!x.__bye&&!y.__bye)p.push([x,y])}out.push(p);a.splice(1,0,a.pop())}return out}
function* perms(arr){const a=[...arr],c=new Array(a.length).fill(0);yield[...a];let i=0,n=1;while(i<a.length&&n<MAX){if(c[i]<i){const j=i%2?c[i]:0;[a[i],a[j]]=[a[j],a[i]];yield[...a];n++;c[i]++;i=0}else{c[i]=0;i++}}}
function option(pairs,g,r,anchor,code,other){let nonBlack=false;for(let mask=0;mask<(1<<pairs.length);mask++){const ps=pairs.map(([a,b],i)=>(mask&(1<<i))?[b,a]:[a,b]),rows=ps.map(([h,a])=>mk(g,r,h,a,anchor,code));if(rows.some(x=>blackout(x,code)))continue;nonBlack=true;if(clean(rows,other))return{pairs:ps,rows,blackoutOnly:false}}return{rows:null,blackoutOnly:!nonBlack}}
function build(order,g,start,interval,code,double,other){const raw=rr(order),chosen=[];let next=new Date(start);for(let i=0;i<raw.length;i++){let placed=null,anchor=null;for(let shift=0;shift<60&&!placed;shift++){anchor=add(next,shift*7);const o=option(raw[i],g,i+1,anchor,code,other);if(o.rows)placed=o;else if(!o.blackoutOnly)return null}if(!placed)return null;chosen.push({...placed,anchor});next=add(anchor,interval*7)}const first=chosen.flatMap(x=>x.rows);if(!double)return first;const ret=[];next=add(chosen[chosen.length-1].anchor,interval*7);for(let i=0;i<chosen.length;i++){let placed=null,anchor=null;for(let shift=0;shift<60&&!placed;shift++){anchor=add(next,shift*7);const rows=chosen[i].pairs.map(([h,a])=>mk(g,i+1+chosen.length,a,h,anchor,code));if(rows.some(x=>blackout(x,code)))continue;if(!clean(rows,[...other,...first,...ret]))return null;placed=rows}if(!placed)return null;ret.push(...placed);next=add(anchor,interval*7)}return[...first,...ret]}
window.buildCalendarPayload=async function(){const sv=document.getElementById('startDate')?.value;if(!sv)throw Error('Inserisci la data di partenza.');await fetchData();if(!groups.length)throw Error('Prima devi creare i gironi.');if(!validateTeams(false))throw Error('Completa prima giorno, ora e campo delle squadre.');const code=document.getElementById('competition').value,double=document.getElementById('formula').value==='double',interval=Number(document.getElementById('interval').value||1),start=from(sv),external=ext(code),payload=[];for(const g of groups){const gt=members.filter(m=>String(m.group_id)===String(g.id)).map(m=>teams.find(t=>String(t.id)===String(m.team_id))).filter(Boolean);if(gt.length<2)continue;let built=null,attempts=0;for(const order of perms(gt)){attempts++;built=build(order,g,start,interval,code,double,[...external,...payload]);if(built)break}if(!built)throw Error(`Non riesco a costruire ${g.name||'il girone'} dopo ${attempts} combinazioni senza violare impianti condivisi, date escluse e ritorno speculare.`);payload.push(...built)}for(let i=0;i<payload.length;i++)for(let j=i+1;j<payload.length;j++)if(conflict(payload[i],payload[j]))throw Error(`Conflitto reale residuo: ${payload[i]._home_name} – ${payload[i]._away_name} / ${payload[j]._home_name} – ${payload[j]._away_name}.`);payload.sort((a,b)=>(a.round_number-b.round_number)||(new Date(a.scheduled_at)-new Date(b.scheduled_at)));payload._calendarDiagnosis={totalMatches:payload.length,conflictsDetected:0,conflictsSolved:0,conflictsUnresolved:0,progression:'OK',rule:'V10.12 FAST · GLOBAL SORT ottimizzato · alternanza impianti condivisi · sospensioni per giornata · ritorno speculare'};return payload};
for(const box of document.querySelectorAll('.notice'))if(/regola calendario|global sort|inversione casa\/trasferta|accavallamenti/i.test(box.textContent||''))box.innerHTML='<b>Regola calendario:</b> GLOBAL SORT ottimizzato con alternanza obbligatoria delle squadre che condividono impianto, giorno e orario. Le <b>date escluse</b> restano rispettate: se una giornata le intercetta viene rinviata interamente. Il ritorno resta speculare. Nessuna partita viene spostata da sola.';
console.info('[V9 calendario] 10.12 FAST attivo');
})();